services:
  - type: web
    name: bitespeed-identity-service
    env: node
    buildCommand: npm run render-build
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: bitespeed-db
          property: connectionString
    autoDeploy: true

databases:
  - name: bitespeed-db
    databaseName: bitespeed_identity
    user: bitespeed_user